import streamlit as st
import os
import google.generativeai as genai
from fpdf import FPDF
from gtts import gTTS
from PIL import Image
import io
import folium
from streamlit_folium import st_folium
from streamlit_lottie import st_lottie
import requests

# ---------------------------------------------------------
# 1. CONFIGURATION & PAGE SETUP
# ---------------------------------------------------------
st.set_page_config(
    page_title="Shahab AI Hospital",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Professional UI
st.markdown("""
<style>
    /* Main Background */
    .stApp {
        background: linear-gradient(to right, #f8f9fa, #e0e7ff);
    }
    /* Sidebar */
    section[data-testid="stSidebar"] {
        background-color: #0f172a;
    }
    /* Chat Bubbles */
    .user-msg {
        background-color: #dbeafe;
        padding: 12px;
        border-radius: 15px;
        margin-bottom: 10px;
        text-align: right;
        color: #1e3a8a;
        font-weight: 500;
        border: 1px solid #bfdbfe;
    }
    .agent-msg {
        background-color: #ffffff;
        padding: 12px;
        border-radius: 15px;
        margin-bottom: 10px;
        box-shadow: 0px 2px 5px rgba(0,0,0,0.05);
        color: #333;
        border: 1px solid #e5e7eb;
    }
    /* Headings */
    h1, h2, h3 {
        color: #1e40af;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# 2. API SETUP & SESSION STATE
# ---------------------------------------------------------

# Retrieve API Key from Secrets
try:
    if "GEMINI_API_KEY" in st.secrets:
        api_key = st.secrets["GEMINI_API_KEY"]
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash') # Using standard model
    else:
        st.error("⚠️ API Key Missing! Please add GEMINI_API_KEY in Streamlit Secrets.")
        st.stop()
except Exception as e:
    st.error(f"Configuration Error: {e}")
    st.stop()

# Session State Initialization
if "history" not in st.session_state:
    st.session_state.history = []
if "vision_analysis" not in st.session_state:
    st.session_state.vision_analysis = "No image uploaded yet."

# ---------------------------------------------------------
# 3. HELPER FUNCTIONS
# ---------------------------------------------------------

def load_lottieurl(url: str):
    try:
        r = requests.get(url)
        if r.status_code != 200:
            return None
        return r.json()
    except:
        return None

def check_emergency(text):
    keywords = ["heart attack", "chest pain", "can't breathe", "unconscious", "stroke", "suicide", "bleeding", "poison"]
    for word in keywords:
        if word in text.lower():
            return True
    return False

def text_to_speech(text):
    try:
        # Limit text length to avoid timeouts
        short_text = text[:300] 
        tts = gTTS(text=short_text, lang='en', tld='co.uk')
        fp = io.BytesIO()
        tts.write_to_fp(fp)
        return fp
    except Exception as e:
        return None

# ---------------------------------------------------------
# 4. PDF GENERATION CLASS
# ---------------------------------------------------------
class UltimateHealthReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'SHAHAB MEDICAL HOSPITAL', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'AI Integrated Medical Center, Islamabad', 0, 1, 'C')
        self.set_draw_color(0, 50, 150)
        self.set_line_width(1)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100)
        self.cell(0, 10, 'CONFIDENTIAL | Generated by AI Agent | Not a substitute for a doctor', 0, 0, 'C')

def create_pdf(chat_history, vision_data):
    pdf = UltimateHealthReport()
    pdf.add_page()
    
    # Use AI to summarize for the PDF
    prompt = f"""
    Summarize this medical consultation for a formal report.
    Chat History: {chat_history}
    Image Findings: {vision_data}
    
    Format nicely as:
    1. Patient Complaint
    2. Symptoms Analysis
    3. Recommendations
    """
    try:
        summary_resp = model.generate_content(prompt)
        text_content = summary_resp.text
    except:
        text_content = "Could not generate summary. Please check internet connection."

    pdf.set_font('Arial', '', 11)
    # Handling Encoding for PDF
    clean_text = text_content.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, clean_text)
    
    return pdf.output(dest='S').encode('latin-1')

# ---------------------------------------------------------
# 5. UI NAVIGATION
# ---------------------------------------------------------

with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3774/3774299.png", width=80)
    st.title("Main Menu")
    page = st.radio("Navigate:", ["🏠 Home", "🤖 AI Doctor", "🗺️ Hospital Locator", "📄 Medical Report"])
    st.markdown("---")
    st.warning("🚑 In Emergency: Call 1122")

# ---------------------------------------------------------
# PAGE: HOME
# ---------------------------------------------------------
if page == "🏠 Home":
    col1, col2 = st.columns([1.2, 1])
    
    with col1:
        st.title("Shahab AI Hospital")
        st.markdown("### Next-Gen Healthcare System")
        st.write("Welcome to your personal medical assistant. Using advanced AI, we provide instant triage, symptom analysis, and hospital navigation.")
        st.info("👈 Select a feature from the sidebar to begin.")
        
    with col2:
        lottie_med = load_lottieurl("https://assets5.lottiefiles.com/packages/lf20_5njp3vgg.json")
        if lottie_med:
            st_lottie(lottie_med, height=350, key="med_anim")

# ---------------------------------------------------------
# PAGE: AI DOCTOR
# ---------------------------------------------------------
elif page == "🤖 AI Doctor":
    st.title("🤖 Dr. AI Consultant")
    
    # --- Image Analysis Section ---
    with st.expander("📸 Upload X-Ray or Prescription", expanded=False):
        uploaded_file = st.file_uploader("Upload Image", type=['png', 'jpg', 'jpeg'])
        if uploaded_file:
            image = Image.open(uploaded_file)
            st.image(image, caption='Uploaded Image', width=200)
            if st.button("Analyze Image"):
                with st.spinner("Analyzing clinical data..."):
                    try:
                        vision_prompt = "Analyze this medical image. If it's a prescription, list the medicines. If it's a symptom, describe it."
                        response = model.generate_content([vision_prompt, image])
                        st.session_state.vision_analysis = response.text
                        st.success("Analysis Complete!")
                        st.session_state.history.append(("AI", f"**[Image Analysis]:** {response.text}"))
                    except Exception as e:
                        st.error(f"Error: {e}")

    # --- Chat Interface ---
    chat_container = st.container()
    with chat_container:
        for role, text in st.session_state.history:
            if role == "User":
                st.markdown(f'<div class="user-msg"><b>You:</b> {text}</div>', unsafe_allow_html=True)
            else:
                st.markdown(f'<div class="agent-msg"><b>Dr. AI:</b> {text}</div>', unsafe_allow_html=True)

    # --- Input Area ---
    user_input = st.chat_input("Describe your symptoms...")
    
    if user_input:
        st.session_state.history.append(("User", user_input))
        
        # Emergency Guardrail
        if check_emergency(user_input):
            alert_msg = "⚠️ CRITICAL ALERT: Based on your input, this may be a medical emergency. Please call 1122 immediately."
            st.session_state.history.append(("AI", alert_msg))
            st.error(alert_msg)
        else:
            try:
                # Construct Context
                full_prompt = f"""
                Act as a professional, empathetic doctor. 
                Context from previous image analysis: {st.session_state.vision_analysis}
                Patient says: {user_input}
                Provide a short, professional medical advice.
                """
                response = model.generate_content(full_prompt)
                ai_reply = response.text
                
                st.session_state.history.append(("AI", ai_reply))
                
                # Voice Output
                audio_bytes = text_to_speech(ai_reply)
                if audio_bytes:
                    st.audio(audio_bytes, format='audio/mp3')
                    
            except Exception as e:
                st.error(f"AI Connection Error: {e}")
        
        st.rerun()

# ---------------------------------------------------------
# PAGE: HOSPITAL MAP
# ---------------------------------------------------------
elif page == "🗺️ Hospital Locator":
    st.title("🏥 Find Nearby Hospitals")
    
    city = st.selectbox("Select City", ["Islamabad", "Lahore", "Karachi"])
    
    # Coordinates Center
    locations = {
        "Islamabad": [33.6844, 73.0479],
        "Lahore": [31.5204, 74.3587],
        "Karachi": [24.8607, 67.0011]
    }
    
    # Mock Data for Display
    hospitals = {
        "Islamabad": [
            {"name": "PIMS Hospital", "lat": 33.7077, "lon": 73.0501, "phone": "051-9261170", "status": "Open 24/7"},
            {"name": "Shifa International", "lat": 33.6766, "lon": 73.1068, "phone": "051-8463666", "status": "Open 24/7"},
            {"name": "Kulsum Int. Hospital", "lat": 33.7042, "lon": 73.0645, "phone": "051-2275765", "status": "Busy"}
        ],
        "Lahore": [
             {"name": "Jinnah Hospital", "lat": 31.4883, "lon": 74.2987, "phone": "042-99231400", "status": "Open"},
             {"name": "General Hospital", "lat": 31.4655, "lon": 74.3570, "phone": "042-99268801", "status": "Open"}
        ],
        "Karachi": [
             {"name": "Aga Khan Hospital", "lat": 24.8926, "lon": 67.0740, "phone": "021-111911911", "status": "Open"},
             {"name": "Indus Hospital", "lat": 24.8450, "lon": 67.1642, "phone": "021-35112709", "status": "Busy"}
        ]
    }

    m = folium.Map(location=locations[city], zoom_start=13)
    
    for h in hospitals[city]:
        # HTML for Popup
        popup_html = f"""
        <div style="font-family: sans-serif; width: 180px;">
            <h5 style="color:red; margin:0;">{h['name']}</h5>
            <hr style="margin: 5px 0;">
            <b>📞:</b> {h['phone']}<br>
            <b>🟢 Status:</b> {h['status']}<br>
            <br>
            <a href="https://www.google.com/maps/dir/?api=1&destination={h['lat']},{h['lon']}" target="_blank"
            style="background:#2563eb; color:white; text-decoration:none; padding:5px 10px; border-radius:5px; font-size:12px;">
            Get Directions ➔
            </a>
        </div>
        """
        folium.Marker(
            [h['lat'], h['lon']],
            popup=folium.Popup(popup_html, max_width=250),
            tooltip=h['name'],
            icon=folium.Icon(color="blue", icon="plus", prefix='fa')
        ).add_to(m)

    st_folium(m, width=1200, height=500)

# ---------------------------------------------------------
# PAGE: REPORT
# ---------------------------------------------------------
elif page == "📄 Medical Report":
    st.title("📄 Patient Discharge Report")
    
    if len(st.session_state.history) > 0:
        st.write("Click below to generate a professional PDF summary of your consultation.")
        if st.button("Generate & Download PDF"):
            with st.spinner("Writing report..."):
                try:
                    pdf_bytes = create_pdf(str(st.session_state.history), st.session_state.vision_analysis)
                    st.download_button(
                        label="📥 Download Report",
                        data=pdf_bytes,
                        file_name="Shahab_Medical_Report.pdf",
                        mime="application/pdf"
                    )
                    st.success("Report Ready!")
                except Exception as e:
                    st.error(f"Failed to generate report: {e}")
    else:
        st.info("Please consult with the AI Doctor first to generate data for the report.")
