import streamlit as st
import os
import time
from google import genai
from fpdf import FPDF
from gtts import gTTS
from PIL import Image
import io
import folium
from streamlit_folium import st_folium
from streamlit_lottie import st_lottie
import requests

# ---------------------------------------------------------
# CONFIGURATION & PAGE SETUP
# ---------------------------------------------------------
st.set_page_config(
    page_title="Shahab AI Hospital",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Professional UI
st.markdown("""
<style>
    /* Main Background */
    .stApp {
        background: linear-gradient(to right, #f8f9fa, #e0e7ff);
    }
    
    /* Sidebar Styling */
    section[data-testid="stSidebar"] {
        background-color: #0f172a;
    }
    
    /* Headers */
    h1, h2, h3 {
        color: #1e3a8a;
        font-family: 'Helvetica', sans-serif;
    }
    
    /* Chat Bubbles */
    .user-msg {
        background-color: #dbeafe;
        padding: 10px;
        border-radius: 10px;
        margin-bottom: 5px;
        text-align: right;
        color: #1e3a8a;
        font-weight: 500;
    }
    .agent-msg {
        background-color: #ffffff;
        padding: 10px;
        border-radius: 10px;
        margin-bottom: 5px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
        color: #333;
    }
    
    /* Buttons */
    .stButton>button {
        background-color: #2563eb;
        color: white;
        border-radius: 8px;
        border: none;
        padding: 10px 20px;
        transition: 0.3s;
    }
    .stButton>button:hover {
        background-color: #1d4ed8;
        transform: scale(1.02);
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# INITIALIZATION (Secrets & Session State)
# ---------------------------------------------------------

# API Key Logic for Streamlit Cloud
# GitHub par key upload nahi karni, Cloud settings me dalni hai
try:
    if "GEMINI_API_KEY" in st.secrets:
        os.environ['GEMINI_API_KEY'] = st.secrets["GEMINI_API_KEY"]
    else:
        st.warning("⚠️ API Key not found in Secrets. Please configure it in Streamlit Cloud.")
except Exception:
    pass # Handle local errors gracefully

client = genai.Client()
model_name = 'gemini-2.5-flash'

# Session State
if "history" not in st.session_state:
    st.session_state.history = []
if "vision_analysis" not in st.session_state:
    st.session_state.vision_analysis = "No image uploaded yet."

# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------

def load_lottieurl(url: str):
    try:
        r = requests.get(url)
        if r.status_code != 200:
            return None
        return r.json()
    except:
        return None

def check_emergency(text):
    keywords = ["heart attack", "chest pain", "can't breathe", "unconscious", "stroke", "suicide", "bleeding", "poison"]
    for word in keywords:
        if word in text.lower():
            return True
    return False

def text_to_speech(text):
    try:
        short_text = text[:300] 
        tts = gTTS(text=short_text, lang='en', tld='co.uk')
        fp = io.BytesIO()
        tts.write_to_fp(fp)
        return fp
    except Exception as e:
        return None

def analyze_image(image):
    try:
        prompt = "Analyze this medical image. If prescription, list medicines. If symptom, describe condition briefly."
        response = client.models.generate_content(model=model_name, contents=[prompt, image])
        return response.text
    except Exception as e:
        return f"Error processing image: {str(e)}"

# ---------------------------------------------------------
# PDF CLASS
# ---------------------------------------------------------
class UltimateHealthReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'SHAHAB MEDICAL HOSPITAL', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'AI Integrated Medical Center, Islamabad', 0, 1, 'C')
        self.set_draw_color(0, 50, 150)
        self.set_line_width(1)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100)
        self.cell(0, 10, 'CONFIDENTIAL | Generated by AI Agent | Not a substitute for a doctor', 0, 0, 'C')

def create_pdf(chat_history, vision_data):
    pdf = UltimateHealthReport()
    pdf.add_page()
    
    prompt = f"""
    Create a medical summary from this chat: {chat_history} 
    and image analysis: {vision_data}.
    Format:
    SECTION 1: PATIENT SUMMARY
    SECTION 2: SYMPTOMS
    SECTION 3: AI RECOMMENDATIONS
    SECTION 4: ROUTINE CHECKLIST
    """
    
    try:
        summary_response = client.models.generate_content(model=model_name, contents=[prompt])
        text_content = summary_response.text
    except:
        text_content = "Summary generation failed."

    pdf.set_font('Arial', '', 11)
    clean_text = text_content.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, clean_text)
    
    return pdf.output(dest='S').encode('latin-1')

# ---------------------------------------------------------
# NAVIGATION & SIDEBAR
# ---------------------------------------------------------

with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3774/3774299.png", width=80)
    st.title("Navigation")
    page = st.radio("Go to:", ["🏠 Home", "🤖 AI Doctor", "🗺️ Hospital Locator", "📄 Medical Report"])
    st.markdown("---")
    st.info("Emergency? Call 1122")

# ---------------------------------------------------------
# PAGE 1: HOME
# ---------------------------------------------------------
if page == "🏠 Home":
    col1, col2 = st.columns([1.2, 1])
    
    with col1:
        st.title("Welcome to Shahab AI Hospital")
        st.markdown("### Your Intelligent Medical Companion")
        st.write("Experience the future of healthcare. Our system provides real-time triage, prescription analysis, and hospital navigation.")
        
        st.success("✅ **Available Features:**\n- 24/7 AI Doctor Consultation\n- Image-based Diagnosis\n- Live Hospital Locator\n- Instant Medical Reports")
        
    with col2:
        lottie_med = load_lottieurl("https://assets5.lottiefiles.com/packages/lf20_5njp3vgg.json")
        if lottie_med:
            st_lottie(lottie_med, height=350, key="med_anim")
        else:
            st.image("https://img.freepik.com/free-vector/doctor-character-background_1270-84.jpg", width=300)

# ---------------------------------------------------------
# PAGE 2: AI DOCTOR (CHAT)
# ---------------------------------------------------------
elif page == "🤖 AI Doctor":
    st.title("🤖 Dr. AI Consultant")
    st.markdown("---")

    # Image Uploader
    with st.expander("📸 Upload Medical Records (X-Ray / Prescription)"):
        uploaded_file = st.file_uploader("Upload Image", type=['png', 'jpg', 'jpeg'])
        if uploaded_file:
            image = Image.open(uploaded_file)
            st.image(image, caption='Uploaded Image', width=200)
            if st.button("Analyze Image"):
                if "GEMINI_API_KEY" not in os.environ:
                     st.error("API Key missing. Cannot analyze.")
                else:
                    with st.spinner("Dr. AI is analyzing..."):
                        result = analyze_image(image)
                        st.session_state.vision_analysis = result
                        st.success("Analysis Complete!")
                        st.session_state.history.append(f"**[Image Analysis]:** {result}")

    # Chat Interface
    chat_container = st.container()
    
    with chat_container:
        for role, text in st.session_state.history:
            if role == "User":
                st.markdown(f'<div class="user-msg"><b>You:</b> {text}</div>', unsafe_allow_html=True)
            elif "**[Image Analysis]:**" in text:
                st.info(text)
            else:
                st.markdown(f'<div class="agent-msg"><b>Dr. AI:</b> {text}</div>', unsafe_allow_html=True)

    user_input = st.chat_input("Type your symptoms here...")

    if user_input:
        if "GEMINI_API_KEY" not in os.environ:
            st.error("Please configure the API Key in Streamlit Secrets first.")
        else:
            st.session_state.history.append(("User", user_input))
            
            if check_emergency(user_input):
                em_msg = "⚠️ CRITICAL ALERT: Please call 1122 or go to the ER immediately."
                st.session_state.history.append(("Agent", em_msg))
                st.error(em_msg)
            else:
                try:
                    context = f"History: {st.session_state.history}. Vision Data: {st.session_state.vision_analysis}. User asked: {user_input}"
                    response = client.models.generate_content(model=model_name, contents=[context])
                    reply = response.text
                    
                    st.session_state.history.append(("Agent", reply))
                    
                    audio_fp = text_to_speech(reply)
                    if audio_fp:
                        st.audio(audio_fp, format='audio/mp3')
                except Exception as e:
                    st.error(f"Error connecting to AI: {e}")

            st.rerun()

# ---------------------------------------------------------
# PAGE 3: HOSPITAL LOCATOR (MAPS)
# ---------------------------------------------------------
elif page == "🗺️ Hospital Locator":
    st.title("🏥 Nearby Hospitals & Availability")
    
    city = st.selectbox("Select Your City", ["Islamabad", "Lahore", "Karachi"])
    
    locations = {
        "Islamabad": [33.6844, 73.0479],
        "Lahore": [31.5204, 74.3587],
        "Karachi": [24.8607, 67.0011]
    }
    
    # Demo Data for Hospitals
    hospitals_data = {
        "Islamabad": [
            {"name": "PIMS Hospital", "lat": 33.7077, "lon": 73.0501, "phone": "051-9261170", "status": "🟢 Open 24/7"},
            {"name": "Shifa International", "lat": 33.6766, "lon": 73.1068, "phone": "051-8463666", "status": "🟢 Open 24/7"},
            {"name": "Maroof Int. Hospital", "lat": 33.6938, "lon": 73.0402, "phone": "051-2222920", "status": "🟠 Busy"}
        ],
        "Lahore": [
            {"name": "Jinnah Hospital", "lat": 31.4883, "lon": 74.2987, "phone": "042-99231400", "status": "🟢 Open"},
            {"name": "Doctors Hospital", "lat": 31.4789, "lon": 74.2801, "phone": "042-35302701", "status": "🟢 Open"}
        ],
        "Karachi": [
            {"name": "Aga Khan Hospital", "lat": 24.8926, "lon": 67.0740, "phone": "021-111911911", "status": "🟢 Open"},
            {"name": "Liaquat National", "lat": 24.8870, "lon": 67.0671, "phone": "021-34412000", "status": "🔴 Emergency Only"}
        ]
    }

    m = folium.Map(location=locations[city], zoom_start=13)
    
    for hosp in hospitals_data[city]:
        html = f"""
        <div style="font-family: sans-serif; width:200px">
            <h5 style="color: #0d47a1; margin-bottom: 5px;">{hosp['name']}</h5>
            <div style="font-size: 12px;">
                <b>Status:</b> {hosp['status']}<br>
                <b>Phone:</b> <a href="tel:{hosp['phone']}">{hosp['phone']}</a><br>
                <br>
                <a href="https://www.google.com/maps/search/?api=1&query={hosp['lat']},{hosp['lon']}" target="_blank" 
                style="background-color: #4CAF50; color: white; padding: 5px 10px; text-decoration: none; border-radius: 4px;">
                📍 Navigate on Google Maps
                </a>
            </div>
        </div>
        """
        popup = folium.Popup(html, max_width=300)
        folium.Marker(
            [hosp['lat'], hosp['lon']],
            popup=popup,
            tooltip=hosp['name'],
            icon=folium.Icon(color="red", icon="plus", prefix='fa')
        ).add_to(m)

    st_folium(m, width=1200, height=500)

# ---------------------------------------------------------
# PAGE 4: MEDICAL REPORT
# ---------------------------------------------------------
elif page == "📄 Medical Report":
    st.title("📄 Generate Medical Report")
    st.write("Download a formal medical summary of your AI consultation.")
    
    if len(st.session_state.history) > 0:
        if st.button("Generate & Download PDF"):
            with st.spinner("Processing Report..."):
                pdf_data = create_pdf(str(st.session_state.history), st.session_state.vision_analysis)
                st.download_button(
                    label="Download PDF Report 📥",
                    data=pdf_data,
                    file_name="Shahab_Medical_Report.pdf",
                    mime="application/pdf"
                )
    else:
        st.info("Start a chat with the AI Doctor to generate data for the report.")